Repository 4GeeksAcademy/sp72-final-project-g2, pull requests merged in 2024-09, with the labels that each got.

#20 AI endpoint
  src/api/models.py
  src/api/routes.py
Labels: bug

#21 AI Frontend
  package-lock.json
  package.json
  src/api/routes.py
  src/app.py
  src/front/js/Layout.jsx
  src/front/js/component/MainNavbar.jsx
  src/front/js/pages/GenerateRecipes.jsx
  src/front/js/pages/GenerateRoutines.jsx
  src/front/js/store/flux.js
Labels: enhancement

#22 BMR Calculator
  src/front/js/Layout.jsx
  src/front/js/component/BmrCalculator.jsx
  src/front/js/component/MainNavbar.jsx
Labels: enhancement

#26 [login_signup] feat: primer login y signup juntos
  src/front/js/pages/Login.jsx
  src/front/js/pages/SignUp.jsx
Labels: enhancement

#29 FRONT: integration of form for trainers
  src/api/routes.py
  src/front/js/Layout.jsx
  src/front/js/component/Alert.jsx
  src/front/js/component/BmrCalculator.jsx
  src/front/js/component/FormTrainer.jsx
  src/front/js/pages/GenerateRecipes.jsx
  src/front/js/pages/GenerateRoutines.jsx
  src/front/js/pages/Trainers.jsx
  src/front/styles/MainNavbar.css
  src/front/styles/Recipe.css
Labels: enhancement

#30 REVISION: part of impruvements
  src/front/js/Layout.jsx
  src/front/js/component/BodyHomeSecondary.jsx
  src/front/js/component/MainNavbar.jsx
  src/front/js/pages/Home.jsx
  src/front/styles/index.css
Labels: enhancement

#31 added tokken expiration to 24h in app.py
  src/app.py
  src/front/js/Layout.jsx
  src/front/js/component/MainNavbar.jsx
  src/front/js/pages/GenerateRecipes.jsx
  src/front/js/store/flux.js
Labels: enhancement

#32 [footer] feat: footer finalizado
  src/front/js/component/Footer.jsx
  src/front/styles/Footer.css
Labels: enhancement

#33 Login signup
  Pipfile
  Pipfile.lock
  migrations/env.py
  migrations/versions/694a1f954f0c_.py
  migrations/versions/7ba6f3dd4cd7_.py
  migrations/versions/b3dd6a36cd66_.py
  package-lock.json
  package.json
  public/img/fitness.jpg
  src/api/Ingredients.json
  src/api/admin.py
  src/api/models.py
  src/api/routes.py
  src/app.py
  src/front/img/LogoWeb.png
  src/front/img/app-fit.jpg
  src/front/img/fitness-home-app-4geeks.png
  src/front/img/fitness-home-app.jpg
  src/front/img/fitness-home.png
  src/front/img/fitness.jpg
  src/front/img/home-equipment.jpg
  src/front/img/home-exercise.jpg
  src/front/img/home-nutrition.jpg
  src/front/img/user.jpg
  src/front/js/Layout.jsx
  src/front/js/component/Alert.jsx
  src/front/js/component/BmrCalculator.jsx
  src/front/js/component/BodyHomeMain.jsx
  src/front/js/component/BodyHomeSecondary.jsx
  src/front/js/component/FormTrainer.jsx
  src/front/js/component/Logout.jsx
  src/front/js/component/MainNavbar.jsx
  src/front/js/component/Navbar.jsx
  src/front/js/pages/Dashboard.jsx
  src/front/js/pages/GenerateRecipes.jsx
  src/front/js/pages/GenerateRoutines.jsx
  src/front/js/pages/Home.jsx
  src/front/js/pages/Login.jsx
  src/front/js/pages/Profile.jsx
  src/front/js/pages/SignUp.jsx
  src/front/js/pages/Trainers.jsx
  src/front/js/store/appContext.js
  src/front/js/store/flux.js
  src/front/styles/MainNavbar.css
  src/front/styles/Recipe.css
  src/front/styles/home.css
  src/front/styles/index.css
  src/front/styles/profile.css
  template.html
Labels: enhancement

#36 Fix login
  src/front/js/pages/Login.jsx
Labels: bug, fix, login

#37 [fix-footer] fix: footer bottom
  src/front/js/Layout.jsx
  src/front/js/component/Footer.jsx
  src/front/styles/Footer.css
Labels: fix

#38 [login-signup] fix: despegado del navbar
  src/front/js/pages/Login.jsx
Labels: fix

#39 [navbar] fix: boton unico para login-signup
  src/front/js/component/MainNavbar.jsx
Labels: fix

#40 Exercises list
  src/api/Exercises.json
  src/api/models.py
  src/api/routes.py
  src/front/js/Layout.jsx
  src/front/js/component/MainNavbar.jsx
  src/front/js/pages/Exercise.jsx
Labels: enhancement

#42 [EXERCISE]: translated exercise.jsx and bmr calculator.jsx and datamodels
  src/api/Exercises.json
  src/front/js/component/BmrCalculator.jsx
  src/front/js/pages/Exercise.jsx
Labels: enhancement

#43 Fix merge
  Pipfile
  Pipfile.lock
  migrations/env.py
  migrations/versions/7ba6f3dd4cd7_.py
  migrations/versions/b3dd6a36cd66_.py
  package-lock.json
  package.json
  public/img/fitness.jpg
  src/api/Ingredients.json
  src/api/admin.py
  src/api/models.py
  src/api/routes.py
  src/app.py
  src/front/img/LogoWeb.png
  src/front/img/app-fit.jpg
  src/front/img/fitness-home-app-4geeks.png
  src/front/img/fitness-home-app.jpg
  src/front/img/fitness-home.png
  src/front/img/fitness.jpg
  src/front/img/home-equipment.jpg
  src/front/img/home-exercise.jpg
  src/front/img/home-nutrition.jpg
  src/front/img/user.jpg
  src/front/js/Layout.jsx
  src/front/js/component/Alert.jsx
  src/front/js/component/BodyHomeMain.jsx
  src/front/js/component/FormTrainer.jsx
  src/front/js/component/Logout.jsx
  src/front/js/component/Navbar.jsx
  src/front/js/pages/Dashboard.jsx
  src/front/js/pages/GenerateRoutines.jsx
  src/front/js/pages/Home.jsx
  src/front/js/pages/SignUp.jsx
  src/front/js/pages/Trainers.jsx
  src/front/js/store/appContext.js
  src/front/js/store/flux.js
  src/front/styles/Recipe.css
  template.html
Labels: fix

#51 [CORRECTIONS]
  src/api/routes.py
  src/front/js/component/BmrCalculator.jsx
  src/front/js/pages/Exercise.jsx
  src/front/js/pages/GenerateRecipes.jsx
  src/front/js/pages/GenerateRoutines.jsx
Labels: enhancement

#54 [trainers] fix: imagenes trainers actualizado
  src/front/img/trainers_img/Trainer-01.webp
  src/front/img/trainers_img/Trainer-02.webp
  src/front/img/trainers_img/Trainer-03.webp
  src/front/img/trainers_img/Trainer-04.webp
  src/front/img/trainers_img/Trainer-05.webp
  src/front/img/trainers_img/Trainer-06.webp
  src/front/img/trainers_img/Trainer-07.webp
  src/front/img/trainers_img/Trainer-08.webp
  src/front/img/trainers_img/Trainer-09.webp
  src/front/img/trainers_img/Trainer-10.webp
  src/front/img/trainers_img/Trainer-11.webp
  src/front/img/trainers_img/Trainer-12.webp
  src/front/js/pages/Trainers.jsx
Labels: enhancement

#56 [ENANCEMENT]: Fixed
  src/api/routes.py
  src/front/js/pages/GenerateRecipes.jsx
  src/front/js/pages/GenerateRoutines.jsx
  src/front/js/store/flux.js
Labels: enhancement

#57 listo
  src/front/js/component/FormTrainer.jsx
  src/front/js/pages/Trainers.jsx
Labels: enhancement
